# IVS PROJEKT 2017

default: all

all:
	python3 -m compileall *.py

pack: doc
	#TODO

clean:
	rm -f *.pyc
	rm -rf __pycache__

test:
	python3 tester.py

doc:
	#TODO

run:
	python3 gui.py

pep:
	pep8 *.py
